spring.application.name=Breaking_Bias

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=2

# AI
spring.ai.google.genai.api-key=${KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# Brevo API (replaces SMTP)
brevo.api.key=${BREVO_API_KEY}

# Server
server.port=${PORT:8080}

# App URLs
app.base-url=${BACKEND_URL}
app.frontend-url=${FRONTEND_URL}

# Session Cookie
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=none
